package org.jdna.media.metadata;

/**
 * Autogenerated Enums -- DO NOT EDIT
 * 
 * If you want to add enums, then edit the metadata.xml and then run the
 * generate-constants target in the extra.xml build file.
 */

public enum MetadataKey {
    TITLE("Title", ""),
    ALBUM("Album", ""),
    ARTIST("Artist", ""),
    ALBUM_ARTIST("AlbumArtist", ""),
    COMPOSER("Composer", ""),
    TRACK("Track", ""),
    TOTAL_TRACKS("TotalTracks", ""),
    YEAR("Year", ""),
    COMMENT("Comment", ""),
    GENRE_LIST("GenreList", ""),
    LANGUAGE("Language", ""),
    MPAA_RATING("MPAARating", ""),
    MPAA_RATING_DESCRIPTION("MPAARatingDescription", ""),
    USER_RATING("UserRating", ""),
    RUNNING_TIME("RunningTime", ""),
    DURATION("Duration", ""),
    DESCRIPTION("Description", ""),
    CAST_MEMBER_LIST("CastMemberList", ""),
    POSTER_ART("PosterArt", ""),
    BACKGROUND_ART("BackgroundArt", ""),
    MEDIA_ART_LIST("MediaArtList", ""),
    ASPECT_RATIO("AspectRatio", ""),
    COMPANY("Company", ""),
    PROVIDER_ID("ProviderId", ""),
    PROVIDER_DATA_URL("ProviderDataUrl", ""),
    RELEASE_DATE("ReleaseDate", ""),
    TV_EPISODE("Episode", ""),
    TV_SEASON("Season", "")

    ;

    private String id, desc;

    MetadataKey(String id, String desc) {
        this.id = id;
        this.desc = desc;
    }

    public String getId() {
        return id;
    }

    public String getDescription() {
        return desc;
    }

    public static MetadataKey valueOfId(String id) throws RuntimeException {
        for (MetadataKey k : MetadataKey.values()) {
            if (k.getId().equals(id)) return k;
        }
        throw new RuntimeException("No Enum in MetadataKey for Id: " + id);
    }
}
