<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	version="1.0">
	<xsl:output method="text" />

	<xsl:template match="/">
package org.jdna.media.metadata;
/**
 * Autogenerated Enums -- DO NOT EDIT
 *
 * If you want to add enums, then edit the metadata.xml and then run the generate-constants target
 * in the extra.xml build file.
 */

public enum MetadataKey {
		<xsl:for-each select="//enum">
			<xsl:if test="position()>1">,
			</xsl:if><xsl:value-of select="@constant"/> (&quot;<xsl:value-of select="@id"/>&quot;, &quot;<xsl:value-of select="@description"/>&quot;)
		</xsl:for-each>
	;
	
	private String id, desc;
	MetadataKey(String id, String desc) {
		this.id = id;
		this.desc = desc;
	}
	
	public String getId() {
		return id;
	}
	
	public String getDescription() {
		return desc;
	}
	
	public static MetadataKey valueOfId(String id) throws RuntimeException {
	    for (MetadataKey k : MetadataKey.values()) {
	       if (k.getId().equals(id)) return k;
	    }
	    throw new RuntimeException("No Enum in MetadataKey for Id: "+ id);
	}
}
	</xsl:template>
</xsl:stylesheet>
