package sagex.api.enums;

/**
 * Unofficial SageTV Generated File - Never Edit
 * Generated Date/Time: 8/11/10 3:51 PM
 * See Official Sage Documentation at <a href='http://download.sage.tv/api/sage/api/AiringAPIEnum.html'>AiringAPIEnum</a>
 * This Generated API is not Affiliated with SageTV.  It is user contributed.
 */
public enum AiringAPIEnum {

SetRecordingName,
GetRecordingName,
GetChannel,
GetAiringChannelName,
GetAiringChannelNumber,
GetAiringDuration,
GetAiringStartTime,
GetAiringEndTime,
GetShow,
GetAiringRatings,
GetScheduleStartTime,
GetScheduleEndTime,
GetScheduleDuration,
GetScheduleRecordingRecurrence,
PrintAiringLong,
PrintAiringMedium,
PrintAiringShort,
GetAiringTitle,
IsWatched,
GetWatchedDuration,
GetWatchedStartTime,
GetWatchedEndTime,
GetRealWatchedStartTime,
GetRealWatchedEndTime,
SetWatched,
SetWatchedTimes,
ClearWatched,
GetLatestWatchedTime,
IsWatchedCompletely,
IsDontLike,
SetDontLike,
ClearDontLike,
IsManualRecord,
IsNotManualOrFavorite,
IsAiringHDTV,
GetTrackNumber,
GetRecordingQuality,
SetRecordingQuality,
IsFavorite,
SetRecordingTimes,
Record,
CancelRecord,
IsAiringObject,
GetParentalRating,
GetExtraAiringDetails,
GetAiringID,
GetAiringForID,
AddAiring,
AddAiringDetailed,
GetMediaFileForAiring,
GetAiringOnAfter,
GetAiringOnBefore,
GetManualRecordProperty,
SetManualRecordProperty
}
